const LOGIN_STATUS = 'LOGIN_STATUS';
const CHANGE_PASSWORD_TOKEN = 'CHANGE_PASSWORD_TOKEN';
const NEWUSER = 'NEWUSER';
const POST_ID = 'POST_ID';
const TOP_TAB_NAME = 'TOP_TAB_NAME';
const ROUTE_NAME = 'ROUTE_NAME';
const GET_DETAILS = 'GET_DETAILS';
const EMERGENCY_CONTACT = 'EMERGENCY_CONTACT';
const LOCATION_STATUS = 'LOCATION_STATUS';
const LOCATION_PERMISSION = 'LOCATION_PERMISSION';
const LOCATION_FLAG = 'LOCATION_FLAG';
const LOCATION_CORDS = 'LOCATION_CORDS';
const CLOCK_POPUP = 'CLOCK_POPUP';
const CLOCK_POP_DATA = 'CLOCK_POP_DATA';
const SHOW_CLOCK_IN = 'SHOW_CLOCK_IN';
const SHOW_CLOCK_OUT = 'SHOW_CLOCK_OUT';
const TAKE_BRAKE = 'TAKE_BRAKE';
const END_BRAKE = 'END_BRAKE';
const START_BRAKE_TIME = 'START_BRAKE_TIME';
const END_BRAKE_TIME = 'END_BRAKE_TIME';
const CLOCK_IN_TIME = 'CLOCK_IN_TIME';
const CLOCK_OUT_TIME = 'CLOCK_OUT_TIME';
const SELECTED_TIME_SHEET = 'SELECTED_TIME_SHEET';
const ADD_TIME_SHEET = 'ADD_TIME_SHEET';
const TIME_SHEET_PREVIEW = 'TIME_SHEET_PREVIEW';
const ALL_TIME_SHEET = 'ALL_TIME_SHEET';
const PROFILE_PIC = 'PROFILE_PIC';
const SET_BASE_URL = 'SET_BASE_URL';

const CLOCK_IN_LIST = 'CLOCK_IN_LIST';

const TODAY_SHIFTS = 'TODAY_SHIFTS';
const TODAY_SHIFTS_OBJ = 'TODAY_SHIFTS_OBJ';

const MESSAGE_TYPE = 'MESSAGE_TYPE';
const MESSAGE_DATA = 'MESSAGE_DATA';

const OFFLINE_API_SAVE = 'OFFLINE_API_SAVE';
const OFF_CLOCK_IN_OBJ = "OFF_CLOCK_IN_OBJ";
const CLEAR_OFFLINE_API = "CLEAR_OFFLINE_API";

const LOG_OUT = 'LOG_OUT';

const SIGN_UP = 'SIGN_UP';
const VERIFY_STATUS = 'VERIFY_STATUS';
const Profile_Update_Details = 'Profile_Update_Details';
const Profile_Upload_My_Avatar = 'Profile_Upload_My_Avatar';
const Get_Work_Types = 'Get_Work_Types';
const Get_Salary_Types = 'Get_Salary_Types';
const Get_Notice_Periods = 'Get_Notice_Periods';
const Add_Current_Job = 'Add_Current_Job';
const Get_Job_Groups = 'Get_Job_Groups';
const Get_Job_Types = 'Get_Job_Types';
const Add_Ideal_Jobs = 'Add_Ideal_Jobs';
const Profile_Upload_My_Files = 'Profile_Upload_My_Files';

const SAVE_NETWORK_STATUS = 'SAVE_NETWORK_STATUS';
const SAVE_UNREAD_MSG_COUNT = 'SAVE_UNREAD_MSG_COUNT';

export default {
  LOGIN_STATUS: LOGIN_STATUS,
  CHANGE_PASSWORD_TOKEN: CHANGE_PASSWORD_TOKEN,
  NEWUSER: NEWUSER,
  POST_ID: POST_ID,
  TOP_TAB_NAME: TOP_TAB_NAME,
  ROUTE_NAME: ROUTE_NAME,
  GET_DETAILS: GET_DETAILS,
  EMERGENCY_CONTACT: EMERGENCY_CONTACT,
  LOCATION_STATUS: LOCATION_STATUS,
  LOCATION_PERMISSION: LOCATION_PERMISSION,
  LOCATION_FLAG: LOCATION_FLAG,
  LOCATION_CORDS: LOCATION_CORDS,
  CLOCK_POPUP: CLOCK_POPUP,
  CLOCK_POP_DATA: CLOCK_POP_DATA,
  SHOW_CLOCK_IN: SHOW_CLOCK_IN,
  SHOW_CLOCK_OUT: SHOW_CLOCK_OUT,
  TAKE_BRAKE: TAKE_BRAKE,
  END_BRAKE: END_BRAKE,
  START_BRAKE_TIME: START_BRAKE_TIME,
  END_BRAKE_TIME: END_BRAKE_TIME,
  CLOCK_IN_TIME: CLOCK_IN_TIME,
  CLOCK_OUT_TIME: CLOCK_OUT_TIME,
  LOG_OUT: LOG_OUT,
  SELECTED_TIME_SHEET: SELECTED_TIME_SHEET,
  ADD_TIME_SHEET: ADD_TIME_SHEET,
  TIME_SHEET_PREVIEW: TIME_SHEET_PREVIEW,
  ALL_TIME_SHEET: ALL_TIME_SHEET,
  PROFILE_PIC,
  PROFILE_PIC,
  CLOCK_IN_LIST: CLOCK_IN_LIST,
  TODAY_SHIFTS: TODAY_SHIFTS,
  TODAY_SHIFTS_OBJ: TODAY_SHIFTS_OBJ,
  MESSAGE_TYPE: MESSAGE_TYPE,
  MESSAGE_DATA: MESSAGE_DATA,
  OFFLINE_API_SAVE:OFFLINE_API_SAVE,
  OFF_CLOCK_IN_OBJ: OFF_CLOCK_IN_OBJ,
  CLEAR_OFFLINE_API:CLEAR_OFFLINE_API,
  SIGN_UP: SIGN_UP,
  VERIFY_STATUS: VERIFY_STATUS,
  Profile_Update_Details: Profile_Update_Details,
  Profile_Upload_My_Avatar: Profile_Upload_My_Avatar,
  Get_Work_Types: Get_Work_Types,
  Get_Salary_Types: Get_Salary_Types,
  Get_Notice_Periods: Get_Notice_Periods,
  Add_Current_Job: Add_Current_Job,
  Get_Job_Groups: Get_Job_Groups,
  Get_Job_Types: Get_Job_Types,
  Add_Ideal_Jobs: Add_Ideal_Jobs,
  Profile_Upload_My_Files: Profile_Upload_My_Files,
  SET_BASE_URL,
  SAVE_NETWORK_STATUS,
  SAVE_UNREAD_MSG_COUNT
};
